/**
 * TEMPORARY enemy art roster imported from assets/pending.local (gitignored, local-only) for quick
 * enemy-art trials. Removable wholesale once the roster is finalized and files renamed to the
 * assets/<key>.png convention. Each entry expands (in registry.ts) into <name>.idle / <name>.walk /
 * <name>.attack descriptors (scale 0.5), aliased (in ./aliases) to its pending.local file;
 * PreloadScene.createAnims builds <name>.<action>.right from frameOffsetY + frameCount. Phaser-free.
 * frameOffsetY: 128 = Tiled_files 3rd row, 192 = PNG/ 4th row, 0 = 128px single-sprite folders.
 */
export interface RosterAnim {
  file: string; // path relative to the assets root, e.g. 'pending.local/Tiled_files/Demon1_Idle_without_shadow.png'
  frames: number; // Math.floor(image width / frameSize)
}
export interface RosterEntry {
  name: string; // globally-unique lowercase key base, e.g. 'demon1'
  frameSize: 64 | 128;
  frameOffsetY: number; // 128 | 192 | 0
  idle: RosterAnim;
  walk: RosterAnim; // a Run animation if present, else Walk
  attack: RosterAnim;
}

export const ENEMY_ROSTER: RosterEntry[] = [
  // --- Category 1: Tiled_files (frameSize 64, 3rd row) ---
  { name: 'demon1', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Demon1_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/Tiled_files/Demon1_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/Tiled_files/Demon1_Attack_without_shadow.png', frames: 20 } },
  { name: 'demon2', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Demon2_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/Tiled_files/Demon2_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/Tiled_files/Demon2_Attack_without_shadow.png', frames: 20 } },
  { name: 'demon3', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Demon3_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/Tiled_files/Demon3_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/Tiled_files/Demon3_Attack_without_shadow.png', frames: 20 } },
  { name: 'golem1', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Golem1_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/Tiled_files/Golem1_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/Tiled_files/Golem1_Attack_without_shadow.png', frames: 18 } },
  { name: 'golem2', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Golem2_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/Tiled_files/Golem2_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/Tiled_files/Golem2_Attack_without_shadow.png', frames: 18 } },
  { name: 'golem3', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Golem3_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/Tiled_files/Golem3_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/Tiled_files/Golem3_Attack_without_shadow.png', frames: 18 } },
  { name: 'imp1', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Imp1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Imp1_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Imp1_Attack_without_shadow.png', frames: 6 } },
  { name: 'imp2', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Imp2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Imp2_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Imp2_Attack_without_shadow.png', frames: 6 } },
  { name: 'imp3', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Imp3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Imp3_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Imp3_Attack_without_shadow.png', frames: 6 } },
  { name: 'lich1', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Lich1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Lich1_Run_without_shadow.png', frames: 6 },
    attack: { file: 'pending.local/Tiled_files/Lich1_Attack_without_shadow.png', frames: 8 } },
  { name: 'lich2', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Lich2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Lich2_Run_without_shadow.png', frames: 6 },
    attack: { file: 'pending.local/Tiled_files/Lich2_Attack_without_shadow.png', frames: 8 } },
  { name: 'lich3', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Lich3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Lich3_Run_without_shadow.png', frames: 6 },
    attack: { file: 'pending.local/Tiled_files/Lich3_Attack_without_shadow.png', frames: 8 } },
  { name: 'lizardman1', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Lizardman1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Lizardman1_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Lizardman1_Attack_without_shadow.png', frames: 7 } },
  { name: 'lizardman2', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Lizardman2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Lizardman2_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Lizardman2_Attack_without_shadow.png', frames: 7 } },
  { name: 'lizardman3', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Lizardman3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Lizardman3_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Lizardman3_Attack_without_shadow.png', frames: 7 } },
  { name: 'skeleton1', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Skeleton1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Skeleton1_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Skeleton1_Attack_without_shadow.png', frames: 9 } },
  { name: 'skeleton2', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Skeleton2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Skeleton2_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Skeleton2_Attack_without_shadow.png', frames: 9 } },
  { name: 'skeleton3', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Skeleton3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/Tiled_files/Skeleton3_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Skeleton3_Attack_without_shadow.png', frames: 9 } },
  { name: 'slime2', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Slime2_Idle_without_shadow.png', frames: 6 },
    walk:   { file: 'pending.local/Tiled_files/Slime2_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Slime2_Attack_without_shadow.png', frames: 11 } },
  { name: 'slime3', frameSize: 64, frameOffsetY: 128,
    idle:   { file: 'pending.local/Tiled_files/Slime3_Idle_without_shadow.png', frames: 6 },
    walk:   { file: 'pending.local/Tiled_files/Slime3_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/Tiled_files/Slime3_Attack_without_shadow.png', frames: 9 } },

  // --- Category 2: PNG/<Folder>/Without_shadow (frameSize 64, 4th row) ---
  { name: 'demon1png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Demon1/Without_shadow/Demon1_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/PNG/Demon1/Without_shadow/Demon1_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/PNG/Demon1/Without_shadow/Demon1_Attack_without_shadow.png', frames: 20 } },
  { name: 'demon2png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Demon2/Without_shadow/Demon2_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/PNG/Demon2/Without_shadow/Demon2_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/PNG/Demon2/Without_shadow/Demon2_Attack_without_shadow.png', frames: 20 } },
  { name: 'demon3png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Demon3/Without_shadow/Demon3_Idle_without_shadow.png', frames: 8 },
    walk:   { file: 'pending.local/PNG/Demon3/Without_shadow/Demon3_Run_without_shadow.png', frames: 16 },
    attack: { file: 'pending.local/PNG/Demon3/Without_shadow/Demon3_Attack_without_shadow.png', frames: 20 } },
  { name: 'imp1png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Imp1/Without_shadow/Imp1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Imp1/Without_shadow/Imp1_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Imp1/Without_shadow/Imp1_Attack_without_shadow.png', frames: 6 } },
  { name: 'imp2png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Imp2/Without_shadow/Imp2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Imp2/Without_shadow/Imp2_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Imp2/Without_shadow/Imp2_Attack_without_shadow.png', frames: 6 } },
  { name: 'imp3png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Imp3/Without_shadow/Imp3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Imp3/Without_shadow/Imp3_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Imp3/Without_shadow/Imp3_Attack_without_shadow.png', frames: 6 } },
  { name: 'lich1png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Lich1/Without_shadow/Lich1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Lich1/Without_shadow/Lich1_Run_without_shadow.png', frames: 6 },
    attack: { file: 'pending.local/PNG/Lich1/Without_shadow/Lich1_Attack_without_shadow.png', frames: 8 } },
  { name: 'lich2png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Lich2/Without_shadow/Lich2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Lich2/Without_shadow/Lich2_Run_without_shadow.png', frames: 6 },
    attack: { file: 'pending.local/PNG/Lich2/Without_shadow/Lich2_Attack_without_shadow.png', frames: 8 } },
  { name: 'lich3png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Lich3/Without_shadow/Lich3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Lich3/Without_shadow/Lich3_Run_without_shadow.png', frames: 6 },
    attack: { file: 'pending.local/PNG/Lich3/Without_shadow/Lich3_Attack_without_shadow.png', frames: 8 } },
  { name: 'lizardman1png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Lizardman1/Without_shadow/Lizardman1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Lizardman1/Without_shadow/Lizardman1_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Lizardman1/Without_shadow/Lizardman1_Attack_without_shadow.png', frames: 7 } },
  { name: 'lizardman2png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Lizardman2/Without_shadow/Lizardman2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Lizardman2/Without_shadow/Lizardman2_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Lizardman2/Without_shadow/Lizardman2_Attack_without_shadow.png', frames: 7 } },
  { name: 'lizardman3png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Lizardman3/Without_shadow/Lizardman3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Lizardman3/Without_shadow/Lizardman3_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Lizardman3/Without_shadow/Lizardman3_Attack_without_shadow.png', frames: 7 } },
  { name: 'skeleton1png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Skeleton1/Without_shadow/Skeleton1_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Skeleton1/Without_shadow/Skeleton1_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Skeleton1/Without_shadow/Skeleton1_Attack_without_shadow.png', frames: 9 } },
  { name: 'skeleton2png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Skeleton2/Without_shadow/Skeleton2_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Skeleton2/Without_shadow/Skeleton2_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Skeleton2/Without_shadow/Skeleton2_Attack_without_shadow.png', frames: 9 } },
  { name: 'skeleton3png', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/PNG/Skeleton3/Without_shadow/Skeleton3_Idle_without_shadow.png', frames: 4 },
    walk:   { file: 'pending.local/PNG/Skeleton3/Without_shadow/Skeleton3_Run_without_shadow.png', frames: 8 },
    attack: { file: 'pending.local/PNG/Skeleton3/Without_shadow/Skeleton3_Attack_without_shadow.png', frames: 9 } },

  // --- Category 3: top-level 128px folders (frameSize 128, single row) ---
  { name: 'black_werewolf', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Black_Werewolf/Idle.png', frames: 8 },
    walk:   { file: 'pending.local/Black_Werewolf/Run.png', frames: 9 },
    attack: { file: 'pending.local/Black_Werewolf/Attack_1.png', frames: 6 } },
  { name: 'copper_golem', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Copper_Golem/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Copper_Golem/Run.png', frames: 8 },
    attack: { file: 'pending.local/Copper_Golem/Attack_1.png', frames: 6 } },
  { name: 'demon_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Demon_1/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Demon_1/Walk.png', frames: 5 },
    attack: { file: 'pending.local/Demon_1/Attack.png', frames: 9 } },
  { name: 'demon_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Demon_2/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Demon_2/Walk.png', frames: 12 },
    attack: { file: 'pending.local/Demon_2/Attack.png', frames: 5 } },
  { name: 'demon_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Demon_3/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Demon_3/Walk.png', frames: 12 },
    attack: { file: 'pending.local/Demon_3/Attack.png', frames: 5 } },
  { name: 'demon_4', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Demon_4/Idle.png', frames: 7 },
    walk:   { file: 'pending.local/Demon_4/Walk.png', frames: 1 },
    attack: { file: 'pending.local/Demon_4/Attack.png', frames: 12 } },
  { name: 'dragon_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Dragon_1/Idle.png', frames: 14 },
    walk:   { file: 'pending.local/Dragon_1/Walk.png', frames: 24 },
    attack: { file: 'pending.local/Dragon_1/Attack_1.png', frames: 8 } },
  { name: 'dragon_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Dragon_2/Idle.png', frames: 14 },
    walk:   { file: 'pending.local/Dragon_2/Walk.png', frames: 24 },
    attack: { file: 'pending.local/Dragon_2/Attack_1.png', frames: 8 } },
  { name: 'dragon_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Dragon_3/Idle.png', frames: 14 },
    walk:   { file: 'pending.local/Dragon_3/Walk.png', frames: 24 },
    attack: { file: 'pending.local/Dragon_3/Attack_1.png', frames: 8 } },
  { name: 'elf_queen_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/elf_queen_1/Idle.png', frames: 7 },
    walk:   { file: 'pending.local/elf_queen_1/Walk.png', frames: 12 },
    attack: { file: 'pending.local/elf_queen_1/Attack_1.png', frames: 6 } },
  { name: 'elf_queen_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/elf_queen_2/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/elf_queen_2/Walk.png', frames: 5 },
    attack: { file: 'pending.local/elf_queen_2/Attack.png', frames: 6 } },
  { name: 'goblin_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Goblin_1/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Goblin_1/Run.png', frames: 8 },
    attack: { file: 'pending.local/Goblin_1/Attack_1.png', frames: 5 } },
  { name: 'goblin_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Goblin_2/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Goblin_2/Run.png', frames: 8 },
    attack: { file: 'pending.local/Goblin_2/Attack_1.png', frames: 5 } },
  { name: 'goblin_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Goblin_3/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Goblin_3/Run.png', frames: 7 },
    attack: { file: 'pending.local/Goblin_3/Attack_1.png', frames: 6 } },
  { name: 'gorgon_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Gorgon_1/Idle.png', frames: 7 },
    walk:   { file: 'pending.local/Gorgon_1/Run.png', frames: 7 },
    attack: { file: 'pending.local/Gorgon_1/Attack_1.png', frames: 16 } },
  { name: 'gorgon_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Gorgon_2/Idle.png', frames: 7 },
    walk:   { file: 'pending.local/Gorgon_2/Run.png', frames: 7 },
    attack: { file: 'pending.local/Gorgon_2/Attack_1.png', frames: 16 } },
  { name: 'gorgon_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Gorgon_3/Idle.png', frames: 7 },
    walk:   { file: 'pending.local/Gorgon_3/Run.png', frames: 7 },
    attack: { file: 'pending.local/Gorgon_3/Attack_1.png', frames: 16 } },
  { name: 'hellhound_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Hellhound_1/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Hellhound_1/Run.png', frames: 6 },
    attack: { file: 'pending.local/Hellhound_1/Attack_1.png', frames: 5 } },
  { name: 'hellhound_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Hellhound_2/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Hellhound_2/Run.png', frames: 6 },
    attack: { file: 'pending.local/Hellhound_2/Attack_1.png', frames: 6 } },
  { name: 'hellhound_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Hellhound_3/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Hellhound_3/Run.png', frames: 6 },
    attack: { file: 'pending.local/Hellhound_3/Attack_1.png', frames: 6 } },
  { name: 'knight_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Knight_1/Idle.png', frames: 4 },
    walk:   { file: 'pending.local/Knight_1/Run.png', frames: 7 },
    attack: { file: 'pending.local/Knight_1/Attack 1.png', frames: 5 } },
  { name: 'knight_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Knight_2/Idle.png', frames: 4 },
    walk:   { file: 'pending.local/Knight_2/Run.png', frames: 7 },
    attack: { file: 'pending.local/Knight_2/Attack 1.png', frames: 5 } },
  { name: 'knight_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Knight_3/Idle.png', frames: 4 },
    walk:   { file: 'pending.local/Knight_3/Run.png', frames: 7 },
    attack: { file: 'pending.local/Knight_3/Attack 1.png', frames: 5 } },
  { name: 'lava_golem', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Lava_golem/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Lava_golem/Run.png', frames: 10 },
    attack: { file: 'pending.local/Lava_golem/Attack_1.png', frames: 5 } },
  { name: 'mimic_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Mimic_1/Idle.png', frames: 1 },
    walk:   { file: 'pending.local/Mimic_1/Walk.png', frames: 11 },
    attack: { file: 'pending.local/Mimic_1/Attack.png', frames: 7 } },
  { name: 'mimic_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Mimic_2/Idle.png', frames: 1 },
    walk:   { file: 'pending.local/Mimic_2/Walk.png', frames: 9 },
    attack: { file: 'pending.local/Mimic_2/Attack.png', frames: 4 } },
  { name: 'mimic_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Mimic_3/Idle.png', frames: 1 },
    walk:   { file: 'pending.local/Mimic_3/Walk.png', frames: 6 },
    attack: { file: 'pending.local/Mimic_3/Attack.png', frames: 7 } },
  { name: 'minotaur_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Minotaur_1/Idle.png', frames: 10 },
    walk:   { file: 'pending.local/Minotaur_1/Walk.png', frames: 12 },
    attack: { file: 'pending.local/Minotaur_1/Attack.png', frames: 5 } },
  { name: 'minotaur_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Minotaur_2/Idle.png', frames: 10 },
    walk:   { file: 'pending.local/Minotaur_2/Walk.png', frames: 12 },
    attack: { file: 'pending.local/Minotaur_2/Attack.png', frames: 5 } },
  { name: 'minotaur_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Minotaur_3/Idle.png', frames: 10 },
    walk:   { file: 'pending.local/Minotaur_3/Walk.png', frames: 12 },
    attack: { file: 'pending.local/Minotaur_3/Attack.png', frames: 4 } },
  { name: 'orc_warrior_brown', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Orc_Warrior_Brown/Idle.png', frames: 7 },
    walk:   { file: 'pending.local/Orc_Warrior_Brown/Run.png', frames: 8 },
    attack: { file: 'pending.local/Orc_Warrior_Brown/Attack_1.png', frames: 5 } },
  { name: 'orc_warrior_green', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Orc_Warrior_Green/Idle.png', frames: 7 },
    walk:   { file: 'pending.local/Orc_Warrior_Green/Run.png', frames: 8 },
    attack: { file: 'pending.local/Orc_Warrior_Green/Attack_1.png', frames: 5 } },
  { name: 'orc_woman', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Orc_Woman/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Orc_Woman/Run.png', frames: 8 },
    attack: { file: 'pending.local/Orc_Woman/Attack_1.png', frames: 6 } },
  { name: 'red_werewolf', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Red_Werewolf/Idle.png', frames: 8 },
    walk:   { file: 'pending.local/Red_Werewolf/Run.png', frames: 9 },
    attack: { file: 'pending.local/Red_Werewolf/Attack_1.png', frames: 6 } },
  { name: 'stone_golem', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Stone_Golem/Idle.png', frames: 6 },
    walk:   { file: 'pending.local/Stone_Golem/Run.png', frames: 6 },
    attack: { file: 'pending.local/Stone_Golem/Attack_1.png', frames: 5 } },
  { name: 'white_werewolf', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/White_Werewolf/Idle.png', frames: 8 },
    walk:   { file: 'pending.local/White_Werewolf/Run.png', frames: 9 },
    attack: { file: 'pending.local/White_Werewolf/Attack_1.png', frames: 6 } },
];
