/**
 * TEMPORARY enemy art roster imported from assets/pending.local (gitignored, local-only) for quick
 * enemy-art trials. Removable wholesale once the roster is finalized and files renamed to the
 * assets/<key>.png convention. Each entry expands (in registry.ts) into <name>.idle / <name>.walk /
 * <name>.attack descriptors (scale 0.5), aliased (in ./aliases) to its pending.local file;
 * PreloadScene.createAnims builds <name>.<action>.right from frameOffsetY + frameCount. Phaser-free.
 */
export interface RosterAnim {
  file: string; // path relative to the assets root, e.g. 'pending.local/Tiled_files/Demon1_Idle_without_shadow.png'
  frames: number; // Math.floor(image width / frameSize)
  forwardPx?: number; // per-anim draw nudge: px in the facing direction (recenter the figure on its hex)
  downPx?: number; // per-anim draw nudge: px downward (vertical seating)
}
export interface RosterEntry {
  name: string; // globally-unique lowercase key base, e.g. 'demon1'
  frameSize: 64 | 128 | 256;
  frameOffsetY: number;
  idle: RosterAnim;
  walk: RosterAnim; // a Run animation if present, else Walk
  attack: RosterAnim;
}

export const ENEMY_ROSTER: RosterEntry[] = [
  { name: 'slime1', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/Tiled_files/Slime1_Idle_without_shadow.png', frames: 6, downPx: 10 },
    walk:   { file: 'pending.local/Tiled_files/Slime1_Run_without_shadow.png', frames: 8, downPx: 10 },
    attack: { file: 'pending.local/Tiled_files/Slime1_Attack_without_shadow.png', frames: 10, downPx: 10 } },
  { name: 'slime2', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/Tiled_files/Slime2_Idle_without_shadow.png', frames: 6, downPx: 10 },
    walk:   { file: 'pending.local/Tiled_files/Slime2_Run_without_shadow.png', frames: 8, downPx: 10 },
    attack: { file: 'pending.local/Tiled_files/Slime2_Attack_without_shadow.png', frames: 11, downPx: 10 } },
  { name: 'slime3', frameSize: 64, frameOffsetY: 192,
    idle:   { file: 'pending.local/Tiled_files/Slime3_Idle_without_shadow.png', frames: 6, downPx: 10 },
    walk:   { file: 'pending.local/Tiled_files/Slime3_Run_without_shadow.png', frames: 8, downPx: 10 },
    attack: { file: 'pending.local/Tiled_files/Slime3_Attack_without_shadow.png', frames: 9, downPx: 10 } },

  { name: 'copper_golem', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Copper_Golem/Idle.png', frames: 6, downPx: -6, forwardPx: 4 },
    walk:   { file: 'pending.local/Copper_Golem/Run.png', frames: 8, downPx: -6, forwardPx: 4 },
    attack: { file: 'pending.local/Copper_Golem/Attack_2.png', frames: 7, downPx: -6, forwardPx: 4 } },
  { name: 'demon_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Demon_2/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Demon_2/Walk.png', frames: 12, downPx: -6 },
    attack: { file: 'pending.local/Demon_2/Attack.png', frames: 5, downPx: -6 } },
  { name: 'demon_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Demon_3/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Demon_3/Walk.png', frames: 12, downPx: -6 },
    attack: { file: 'pending.local/Demon_3/Attack.png', frames: 5, downPx: -6 } },
  { name: 'dragon_1', frameSize: 256, frameOffsetY: 0,
    idle:   { file: 'pending.local/Dragon_1/Idle.png', frames: 8, downPx: -16 },
    walk:   { file: 'pending.local/Dragon_1/Walk.png', frames: 12, downPx: -16, forwardPx: 6 },
    attack: { file: 'pending.local/Dragon_1/Attack_2.png', frames: 10, downPx: -16, forwardPx: 18 } },
  { name: 'dragon_2', frameSize: 256, frameOffsetY: 0,
    idle:   { file: 'pending.local/Dragon_2/Idle.png', frames: 8, downPx: -16 },
    walk:   { file: 'pending.local/Dragon_2/Walk.png', frames: 12, downPx: -16, forwardPx: 6 },
    attack: { file: 'pending.local/Dragon_2/Attack_2.png', frames: 10, downPx: -16, forwardPx: 18 } },
  { name: 'dragon_3', frameSize: 256, frameOffsetY: 0,
    idle:   { file: 'pending.local/Dragon_3/Idle.png', frames: 8, downPx: -16 },
    walk:   { file: 'pending.local/Dragon_3/Walk.png', frames: 12, downPx: -16, forwardPx: 6 },
    attack: { file: 'pending.local/Dragon_3/Attack_2.png', frames: 10, downPx: -16, forwardPx: 18 } },
  { name: 'elf_queen_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/elf_queen_1/Idle.png', frames: 7, downPx: -6 },
    walk:   { file: 'pending.local/elf_queen_1/Walk.png', frames: 12, downPx: -6 },
    attack: { file: 'pending.local/elf_queen_1/Summoning.png', frames: 14, downPx: -6 } },
  { name: 'elf_queen_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/elf_queen_2/Idle.png', frames: 6, downPx: -2 },
    walk:   { file: 'pending.local/elf_queen_2/Walk.png', frames: 5, downPx: 0 },
    attack: { file: 'pending.local/elf_queen_2/Attack.png', frames: 6, downPx: -2, forwardPx: 4 } },
  { name: 'goblin_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Goblin_1/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Goblin_1/Run.png', frames: 8, downPx: -6 },
    attack: { file: 'pending.local/Goblin_1/Attack_2.png', frames: 6, downPx: -6, forwardPx: 4 } },
  { name: 'goblin_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Goblin_2/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Goblin_2/Run.png', frames: 8, downPx: -6 },
    attack: { file: 'pending.local/Goblin_2/Attack_3.png', frames: 7, downPx: -6, forwardPx: -4 } },
  { name: 'goblin_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Goblin_3/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Goblin_3/Run.png', frames: 7, downPx: -6 },
    attack: { file: 'pending.local/Goblin_3/Attack_2.png', frames: 6, downPx: -6 } },
  { name: 'gorgon_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Gorgon_1/Idle.png', frames: 7, downPx: -6, forwardPx: 6 },
    walk:   { file: 'pending.local/Gorgon_1/Run.png', frames: 7, downPx: -6 },
    attack: { file: 'pending.local/Gorgon_1/Attack_2.png', frames: 7, downPx: -6, forwardPx: -2 } },
  { name: 'gorgon_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Gorgon_2/Idle.png', frames: 7, downPx: -6 },
    walk:   { file: 'pending.local/Gorgon_2/Run.png', frames: 7, downPx: -6 },
    attack: { file: 'pending.local/Gorgon_2/Attack_2.png', frames: 7, downPx: -6, forwardPx: 2 } },
  { name: 'gorgon_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Gorgon_3/Idle.png', frames: 7, downPx: -6, forwardPx: 4 },
    walk:   { file: 'pending.local/Gorgon_3/Run.png', frames: 7, downPx: -6 },
    attack: { file: 'pending.local/Gorgon_3/Attack_2.png', frames: 7, downPx: -6, forwardPx: -4 } },
  { name: 'knight_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Knight_1/Idle.png', frames: 4, downPx: -6, forwardPx: 16 },
    walk:   { file: 'pending.local/Knight_1/Walk.png', frames: 8, downPx: -6, forwardPx: 16 },
    attack: { file: 'pending.local/Knight_1/Run+Attack.png', frames: 6, downPx: -6, forwardPx: 14 } },
  { name: 'knight_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Knight_2/Idle.png', frames: 4, downPx: -6, forwardPx: 16 },
    walk:   { file: 'pending.local/Knight_2/Walk.png', frames: 8, downPx: -6, forwardPx: 16 },
    attack: { file: 'pending.local/Knight_2/Run+Attack.png', frames: 6, downPx: -6, forwardPx: 14 } },
  { name: 'knight_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Knight_3/Idle.png', frames: 4, downPx: -6, forwardPx: 16 },
    walk:   { file: 'pending.local/Knight_3/Walk.png', frames: 8, downPx: -6, forwardPx: 16 },
    attack: { file: 'pending.local/Knight_3/Run+Attack.png', frames: 6, downPx: -6, forwardPx: 14 } },
  { name: 'lava_golem', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Lava_golem/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Lava_golem/Run.png', frames: 10, downPx: -6 },
    attack: { file: 'pending.local/Lava_golem/Attack_3.png', frames: 7, downPx: -6, forwardPx: 4 } },
  { name: 'mimic_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Mimic_1/Idle.png', frames: 1, downPx: -6, forwardPx: -2 },
    walk:   { file: 'pending.local/Mimic_1/Walk.png', frames: 11, downPx: -6 },
    attack: { file: 'pending.local/Mimic_1/Attack.png', frames: 7, downPx: -6, forwardPx: 4 } },
  { name: 'mimic_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Mimic_2/Idle.png', frames: 1, downPx: -6 },
    walk:   { file: 'pending.local/Mimic_2/Walk.png', frames: 9, downPx: -6 },
    attack: { file: 'pending.local/Mimic_2/Attack.png', frames: 4, downPx: -6, forwardPx: 4 } },
  { name: 'mimic_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Mimic_3/Idle.png', frames: 1, downPx: -6 },
    walk:   { file: 'pending.local/Mimic_3/Walk.png', frames: 6, downPx: -6 },
    attack: { file: 'pending.local/Mimic_3/Attack.png', frames: 7, downPx: -6, forwardPx: 4 } },
  { name: 'minotaur_1', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Minotaur_1/Idle.png', frames: 10, downPx: -6, forwardPx: 2 },
    walk:   { file: 'pending.local/Minotaur_1/Walk.png', frames: 12, downPx: -6, forwardPx: 2 },
    attack: { file: 'pending.local/Minotaur_1/Attack.png', frames: 5, downPx: -6, forwardPx: 6 } },
  { name: 'minotaur_2', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Minotaur_2/Idle.png', frames: 10, downPx: -6, forwardPx: 2 },
    walk:   { file: 'pending.local/Minotaur_2/Walk.png', frames: 12, downPx: -6, forwardPx: 2 },
    attack: { file: 'pending.local/Minotaur_2/Attack.png', frames: 5, downPx: -6, forwardPx: 4 } },
  { name: 'minotaur_3', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Minotaur_3/Idle.png', frames: 10, downPx: -6, forwardPx: 2 },
    walk:   { file: 'pending.local/Minotaur_3/Walk.png', frames: 12, downPx: -6, forwardPx: 2 },
    attack: { file: 'pending.local/Minotaur_3/Attack.png', frames: 4, downPx: -6, forwardPx: 4 } },
  { name: 'orc_warrior_brown', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Orc_Warrior_Brown/Idle.png', frames: 7, downPx: -6 },
    walk:   { file: 'pending.local/Orc_Warrior_Brown/Walk.png', frames: 8, downPx: -6 },
    attack: { file: 'pending.local/Orc_Warrior_Brown/Attack_1.png', frames: 5, downPx: -6, forwardPx: -2 } },
  { name: 'orc_warrior_green', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Orc_Warrior_Green/Idle.png', frames: 7, downPx: -6 },
    walk:   { file: 'pending.local/Orc_Warrior_Green/Walk.png', frames: 8, downPx: -6 },
    attack: { file: 'pending.local/Orc_Warrior_Green/Attack_1.png', frames: 5, downPx: -6, forwardPx: 2 } },
  { name: 'orc_woman', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Orc_Woman/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Orc_Woman/Run.png', frames: 8, downPx: -6 },
    attack: { file: 'pending.local/Orc_Woman/Run+Attack.png', frames: 6, downPx: -6, forwardPx: 2 } },
  { name: 'stone_golem', frameSize: 128, frameOffsetY: 0,
    idle:   { file: 'pending.local/Stone_Golem/Idle.png', frames: 6, downPx: -6 },
    walk:   { file: 'pending.local/Stone_Golem/Run.png', frames: 6, downPx: -6 },
    attack: { file: 'pending.local/Stone_Golem/Attack_1.png', frames: 5, downPx: -6 } },
];
